# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
    # Schedule updates (each 8 hours)
    schedule: [{ cron: "0 */8 * * *" }]
    # Lines below let you run workflow manually and on each commit
    workflow_dispatch:
    push: { branches: ["main"] }

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@master
              with:
                  token: ${{ secrets.METRICS_TOKEN }}

                  # Options
                  user: ShuYingJiYu
                  template: classic
                  base: header, activity, community, repositories, metadata
                  base_hireable: yes
                  config_octicon: yes
                  config_timezone: Asia/Shanghai

                  plugin_languages: yes
                  plugin_languages_analysis_timeout: 15
                  plugin_languages_analysis_timeout_repositories: 7.5
                  plugin_languages_categories: markup, programming
                  plugin_languages_colors: github
                  plugin_languages_ignored: Mathematica, Jupyter Notebook, Starlark, BibTeX Style, Tex, Shell
                  plugin_languages_limit: 8
                  plugin_languages_recent_categories: markup, programming
                  plugin_languages_recent_days: 14
                  plugin_languages_recent_load: 300
                  plugin_languages_sections: most-used
                  plugin_languages_threshold: 0%

                  plugin_lines: yes
                  plugin_lines_history_limit: 1
                  plugin_lines_repositories_limit: 4
                  plugin_lines_sections: base

                  plugin_traffic: yes

                  plugin_people: yes
                  plugin_people_types: followers, contributors, stargazers, watchers, sponsors

                  plugin_activity: yes
                  plugin_activity_limit: 5
                  plugin_activity_days: 0
                  plugin_activity_filter: issue, pr, release, fork, review, ref/create

                  plugin_code: yes
                  plugin_code_languages: javascript, typescript, c, c++, python, java, vue
                  plugin_code_load: 1000
